// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/Nidasakinaa",
            "email": "714220040@std.ulbi.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pasien": {
            "get": {
                "description": "Mengambil semua data pasien.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pasien"
                ],
                "summary": "Get All Data Pasien.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Biodata"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Biodata": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "doctor": {
                    "$ref": "#/definitions/controller.Doctor"
                },
                "gender": {
                    "type": "string"
                },
                "medicalRecord": {
                    "$ref": "#/definitions/controller.MedicalRecord"
                },
                "pasienName": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "ttl": {
                    "type": "string"
                }
            }
        },
        "controller.Doctor": {
            "type": "object",
            "properties": {
                "contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "specialty": {
                    "type": "string"
                }
            }
        },
        "controller.MedicalRecord": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "diagnosis": {
                    "type": "string"
                },
                "doctor": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "treatment": {
                    "type": "string"
                },
                "visitdate": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ws-rumahsakit-2e1eb71f14e2.herokuapp.com",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "TES SWAGGER PASIEN",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
